// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6a49xx5_p2rElGrZNIvhs9LnrDcJlhGE',
    appId: '1:397542434205:web:ba296854d035e7fcbcbb74',
    messagingSenderId: '397542434205',
    projectId: 'map-app-54d0c',
    authDomain: 'map-app-54d0c.firebaseapp.com',
    storageBucket: 'map-app-54d0c.appspot.com',
    measurementId: 'G-ZWQ1BK2NV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCA4MAK_UpokeMlMKyrOhdMuzK7Ear8yI',
    appId: '1:397542434205:android:c1fbec436c1279dabcbb74',
    messagingSenderId: '397542434205',
    projectId: 'map-app-54d0c',
    storageBucket: 'map-app-54d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyugxMDCOF2bjQP07kzvpe5fXjD_mN9c',
    appId: '1:397542434205:ios:00ec449c0fd2be57bcbb74',
    messagingSenderId: '397542434205',
    projectId: 'map-app-54d0c',
    storageBucket: 'map-app-54d0c.appspot.com',
    iosClientId: '397542434205-v1t6jm0b686ujcqdf6amc0u2nbvrj5b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyugxMDCOF2bjQP07kzvpe5fXjD_mN9c',
    appId: '1:397542434205:ios:2a0c264155a7c86bbcbb74',
    messagingSenderId: '397542434205',
    projectId: 'map-app-54d0c',
    storageBucket: 'map-app-54d0c.appspot.com',
    iosClientId: '397542434205-bkctp6ebj8suqt55qf82jh29u4qodi6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapApp.RunnerTests',
  );
}
